name: melodify_app_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.3.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MonFontsBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: MonFontsExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: MonFontsMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MonFontsRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MonFontsSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

    - family: RobotoBlackFont
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
    - family: RobotoBoldFont
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
    - family: RobotoMediumFont
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
    - family: RobotoRegularFont
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
  assets:
    - assets/images/
